[versions]
java = "21"
kotlin = "2.3.0"
kotlinLang = "2.3"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
resilience4j = "2.1.0"
junit5 = "6.0.1"
ksp = "2.3.4"
kotlin-poet = "2.2.0"
ktlint = "1.8.0"
ktlint-gradle = "14.0.1"
detekt = "2.0.0-alpha.1"
kotlin-compile-testing = "1.6.0"
mockk = "1.14.7"
jupiter = "5.10.2"
ktor-client = "3.3.3"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

# Kotlinx
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# KSP (Kotlin Symbol Processing)
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }
kotlin-poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlin-poet" }

# Test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# KtLint
ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }

# Detekt
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-core = { module = "dev.detekt:detekt-core", version.ref = "detekt" }
detekt-gradle-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }

# HTTP Client
# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-client" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-client" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor-client" }

[bundles]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint-gradle-plugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
